language: node_js
compiler: default
matrix:
  exclude:
  # Disable the default build and use customized matrix only.
  - compiler: default
  include:
  # Node 6.x                 Linux (Precise)          G++5.4.1
  - os: linux
    dist: precise
    node_js: '6'
    compiler: g++-5
    addons:
      apt:
        # The apt source 'ubuntu-toolchain-r-test' is for GCC 5+
        # The apt source 'george-edison55-precise-backports' is for CMake 3.2+
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - g++-5
        - cmake-data
        - cmake
    env:
    - COMPILER_OVERRIDE="CXX=g++-5 CC=gcc-5"
  # Node 6.x                 OS X (Yosemite)          AppleClang 6.1
  - os: osx
    node_js: '6'
    osx_image: xcode6.4
  # Node LTS (8.x)           Linux (Trusty)           G++6.4.0
  - os: linux
    dist: trusty
    node_js: '8'
    compiler: g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER_OVERRIDE="CXX=g++-6 CC=gcc-6"
  # Node LTS (8.x)           OS X (El Capitan)        AppleClang 7.3
  - os: osx
    node_js: '8'
    osx_image: xcode7.3
  # Node (9.x)               Linux (Trusty)           G++6.4.0
  - os: linux
    dist: trusty
    node_js: '9'
    compiler: g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER_OVERRIDE="CXX=g++-6 CC=gcc-6"
  # Node (9.x)               macOS (Sierra)           AppleClang 8.1
  - os: osx
    node_js: '9'
    osx_image: xcode8.3
  # Node Current (10.x)       Linux (Trusty)          G++7.3.0
  - os: linux
    dist: trusty
    node_js: '10'
    compiler: g++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - COMPILER_OVERRIDE="CXX=g++-7 CC=gcc-7"
  # Node Current (10.x)       macOS (High Sierra)     AppleClang 9.1
  - os: osx
    node_js: '10'
    osx_image: xcode9.3

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    export ${COMPILER_OVERRIDE}
  fi
install:
- npm install cmake-js -g
- npm install --no-fetch
script:
- npm test
- npm run unittest
