environment:
  matrix:
    # Windows Server 2012 R2       Visual C++ Build Tools 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      nodejs_version: 6
    # Windows Server 2012 R2       Visual C++ Build Tools 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      nodejs_version: 8
    # Windows Server 2016          Visual C++ Build Tools 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      nodejs_version: 9
    # Windows Server 2016          Visual C++ Build Tools 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      nodejs_version: 10

platform:
- x64

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install cmake-js -g
- npm install --no-fetch

# Skip MSBuild stage
build: off

test_script:
- npm test
- npm run unittest
